#!/bin/sh

# proper:bytes traffic monitor

# PROVIDE: probytesd
# REQUIRE: DAEMON LOGIN cleanvar
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable probytesd:
#
#  probytesd_enable="YES"
#  # optional
#  probytesd_user="www"
#  probytesd_group="www"

. /etc/rc.subr

# defaults
probytesd_enable=${probytesd_enable:-"NO"}
probytesd_user=${probytesd_user:-"www"}
probytesd_group=${probytesd_group:-"www"}

name=probytesd
rcvar=probytesd_enable

command="/usr/local/sbin/${name}"
command_args="-u ${probytesd_user} -g ${probytesd_group}"
command_interpreter="ruby"

pidfile="/var/run/${name}.pid"
required_files="/usr/local/etc/${name}.conf.rb"

# handled by daemon, not by rc.subr
unset probytesd_user
unset probytesd_group

# make ruby available
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

load_rc_config $name
run_rc_command "$1"
